### ISSUE TITLE
Cabal version mismatch, when using with stack project

### ISSUE THREAD

**Issue by miuirussia** [Infinisil/all-hies#40] opened 2020-01-09 17:07 UTC
NIX version:
```
nix --version
nix (Nix) 2.3.1
```

nixpkgs revision:
```
a8fc904c7c0d66f07d22bcb59a46d2bd72f8ddae
```

all-hies revision:
4b984030c8080d944372354a7b558c49858057e7

Stack version:
```
stack --version
2.1.3.1 x86_64 hpack-0.33.0
```

GHC version:
```
stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```

HIE language server output:
```
2020-01-09 19:11:33.384471 [ThreadId 4] - Run entered for HIE(hie-8.6.5) Version 1.0.0.0 x86_64 ghc-8.6.5
2020-01-09 19:11:33.385138 [ThreadId 4] - Operating as a LSP server on stdio
2020-01-09 19:11:33.385178 [ThreadId 4] - Current directory:<REDACTED>
2020-01-09 19:11:33.385213 [ThreadId 4] - Operating system:darwin
2020-01-09 19:11:33.385243 [ThreadId 4] - args:["--lsp"]
2020-01-09 19:11:33.388516 [ThreadId 4] - Cabal-Helper decided to use: ProjLocStackYaml {plStackYaml = "<REDACTED>/stack.yaml"}
2020-01-09 19:11:38.316226 [ThreadId 4] - Module "<REDACTED>/File.hs" is loaded by Cradle: Cradle {cradleRootDir = "<REDACTED>", cradleOptsProg = CradleAction: Cabal-Helper-Stack}
2020-01-09 19:11:38.316462 [ThreadId 4] - Use Stack GHC
2020-01-09 19:11:40.38797 [ThreadId 30] - Use Stack GHC
Using hie version: Version 1.0.0.0 x86_64 ghc-8.6.5
2020-01-09 19:11:42.414399 [ThreadId 36] - New cradle: <REDACTED>/src/<REDACTED>.hs
2020-01-09 19:11:42.416678 [ThreadId 36] - Cabal-Helper decided to use: ProjLocStackYaml {plStackYaml = "<REDACTED>/stack.yaml"}
Using hoogle db at: /Users/kirill/.hoogle/default-haskell-5.0.17.hoo
2020-01-09 19:11:47.275474 [ThreadId 36] - Module "<REDACTED>/src/<REDACTED>.hs" is loaded by Cradle: Cradle {cradleRootDir = "<REDACTED>", cradleOptsProg = CradleAction: Cabal-Helper-Stack}
2020-01-09 19:11:47.275569 [ThreadId 36] - Found cradle: Cradle {cradleRootDir = "<REDACTED>", cradleOptsProg = CradleAction: Cabal-Helper-Stack}
[1 of 5] Compiling CabalHelper.Shared.Common ( <REDACTED>/.stack-work/cabal-helper/CabalHelper/Shared/Common.hs, <REDACTED>/.stack-work/cabal-helper/CabalHelper/Shared/Common.o )
[2 of 5] Compiling CabalHelper.Shared.InterfaceTypes ( <REDACTED>/.stack-work/cabal-helper/CabalHelper/Shared/InterfaceTypes.hs, <REDACTED>/.stack-work/cabal-helper/CabalHelper/Shared/InterfaceTypes.o )
[3 of 5] Compiling CabalHelper.Runtime.Compat ( <REDACTED>/.stack-work/cabal-helper/CabalHelper/Runtime/Compat.hs, <REDACTED>/.stack-work/cabal-helper/CabalHelper/Runtime/Compat.o )
[4 of 5] Compiling CabalHelper.Runtime.HelperMain ( <REDACTED>/.stack-work/cabal-helper/CabalHelper/Runtime/HelperMain.hs, <REDACTED>/.stack-work/cabal-helper/CabalHelper/Runtime/HelperMain.o )
[5 of 5] Compiling Main             ( <REDACTED>/.stack-work/cabal-helper/CabalHelper/Runtime/Main.hs, <REDACTED>/.stack-work/cabal-helper/Main.o )
Linking <REDACTED>/.stack-work/cabal-helper/cabal-helper ...
cabal-helper: Saved package config file is outdated:
• the Cabal version changed from Cabal-2.4.1.0 to Cabal-2.4.0.1
Re-run the 'configure' command.
2020-01-09 19:11:54.687849 [ThreadId 30] - Scheduler thread exited unexpectedly: panic! invokeHelper: <REDACTED>/.stack-work/cabal-helper/cabal-helper "<REDACTED>/<REDACTED>.cabal" "<REDACTED>/.stack-work/dist/x86_64-osx-nix/Cabal-2.4.0.1" "v2" "package-id" "compiler-id" "flags" "config-flags" "non-default-config-flags" "component-info" failed!
```

**Comment by fendor** [comment] 2020-01-09 22:33
Can not reproduce with all-hies. Please more information, does it happen on all projects or only one? If only one, can you maybe share it?

**Comment by miuirussia** [comment] 2020-01-10 05:29
It’s happens with home-manager, which installs all-hies globally. Selector: (all-hies.selection { selector = p: { inherit (p) ghc865; }; })

**Comment by miuirussia** [comment] 2020-01-10 05:33
I suspect the error in generated/stable/stack2nix/ghc865.nix, because ghc865 should use Cabal 2.4.0.1, not 2.4.1.0

```
"Cabal" = callPackage
        ({ mkDerivation, array, base, binary, bytestring, containers
         , deepseq, directory, filepath, mtl, parsec, pretty, process
         , stdenv, text, time, transformers, unix
         }:
         mkDerivation {
           pname = "Cabal";
           version = "2.4.1.0";
           sha256 = "736a902da9fb2c826e75e9f7b4b591983bf58a6a62c8cae9866f6a9d5ace3594";
           revision = "2";
           editedCabalFile = "04kg5xh8yabmp1ymk32gw2r66l76338rsglq8i4j2913bhq23vwa";
           setupHaskellDepends = [ mtl parsec ];
           libraryHaskellDepends = [
             array base binary bytestring containers deepseq directory filepath
             mtl parsec pretty process text time transformers unix
           ];
           doHaddock = false;
           doCheck = false;
           homepage = "http://www.haskell.org/cabal/";
           description = "A framework for packaging Haskell software";
           license = stdenv.lib.licenses.bsd3;
         }) {};
```

**Comment by fendor** [comment] 2020-01-10 13:39
Probably a bug in cabal-helper, I can reproduce without using `all-hies`.

**Comment by infinisil** [comment] 2020-01-10 14:48
Closing because unrelated to all-hies, see https://github.com/haskell/haskell-ide-engine/issues/1568 for further tracking

If you want to use an older HIE version temporarily to get around this you could do so by using
```nix
fetchTarball "https://github.com/infinisil/all-hies/tarball/85fd0be92443ca60bb649f8e7748f785fe870b7a"
```
 instead of `master`

**Closed as completed by infinisil** 2020-01-10 14:48 UTC
